apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webapp-node
spec:
  destination:
    name: ''
    namespace: myapp
    server: 'https://kubernetes.default.svc'
  source:
    path: helm-charts
    repoURL: 'https://github.com/das-santu/webapp-node-cicd.git'
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
