apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-node
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: webapp-node
  template:
    metadata:
      labels:
        app: webapp-node
    spec:
      containers:
        - image: santu440/webapp-node:1.0.0
          name: webapp-node
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
          ports:
            - containerPort: 3000
