# This workflow will install Node dependencies, run tests and lint with a single version of Node

name: Node Web App

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Node 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Install dependencies
        run: npm install
      - name: Code Format Testing
        run: |
          npm run format
      - name: Code Lint Testing
        run: |
          npm run lint
      - name: Unit Testing
        run: |
          npm run test
